DetailPrint "Registering Sharity URL"
DeleteRegKey HKCR "Sharity"
WriteRegStr HKCR "Sharity" "" "Sharity File Sharing"
WriteRegStr HKCR "Sharity" "URL Protocol" ""
WriteRegStr HKCR "Sharity\DefaultIcon" "" "$INSTDIR\bin\sharity-client.exe"
WriteRegStr HKCR "Sharity\shell" "" ""
WriteRegStr HKCR "Sharity\shell\open" "" ""
WriteRegStr HKCR "Sharity\shell\open\command" "" "$\"$INSTDIR\bin\sharity-client.exe$\" $\"%1$\""
