name: build-windows.yml
on:
  push:
    branches: [ 'actions', 'main' ]

jobs:
  build-nsis:
    name: Build and Package NSIS
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v5

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.9.1'
          target: 'desktop'
          arch: 'win64_msvc2022_64'

      - name: Install CMake
        uses: ssrobins/install-cmake@v1

      - name: Cache LibDataChannel
        id: cache-libdatachannel
        uses: actions/cache@v4
        with:
          path: 'C:/Program Files (x86)/libdatachannel'
          key: ${{ runner.os }}-libdatachannel

      - name: Build LibDataChannel
        if: steps.cache-libdatachannel.outputs.cache-hit != 'true'
        run: |
          cd ..
          git clone https://github.com/paullouisageneau/libdatachannel.git
          cd libdatachannel
          git checkout v0.23.1
          git submodule update --init --recursive --depth 1
          cmake -B build -G "Visual Studio 17 2022" -DNO_EXAMPLES=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          cmake --install build

      - uses: dtolnay/rust-toolchain@stable
        name: Install Rust

      - name: Build Vodozemac Bindings
        run: |
          cd vodozemac
          cargo build

      - name: Build Sharity
        run: |
          cd client
          cmake -B build  -G "Visual Studio 17 2022" -DQt6_DIR="C:\Qt\6.9.1\msvc2022_64" -DCONFIGURE_NSIS=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Pacakge NSIS
        run: |
          cd client/build
          cpack .